lockfileFilename: "yarn-berry.lock"
nodeLinker: "node-modules"
yarnPath: ".yarn/releases/yarn-3.1.1.cjs"
checksumBehavior: "update"
defaultSemverRangePrefix: ""
enableTelemetry: false
preferInteractive: true
