checksumBehavior: update

defaultSemverRangePrefix: ""

enableTelemetry: false

lockfileFilename: yarn-berry.lock

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"

preferInteractive: false

yarnPath: .yarn/releases/yarn-3.2.1.cjs
