FROM mcr.microsoft.com/dotnet/core/sdk:3.1-focal as base
RUN apt update \
    && apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt install -y nodejs libgomp1 \
    && npm install -g yarn

FROM base as dependencies
WORKDIR /src/Composer
COPY Composer /src/Composer
RUN find . -type f ! \( -name "package.json" -o -name "yarn.lock" \) | xargs rm -rf

RUN yarn install --frozen-lockfile

FROM dependencies as build
WORKDIR /src/Composer
COPY Composer /src/Composer
COPY extensions /src/extensions

ENV NODE_ENV "production"
ENV COMPOSER_BUILTIN_EXTENSIONS_DIR "/src/extensions"
RUN yarn build:dev
