/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import { __extends } from "tslib";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ApplicationInsightsManagementClientContext } from "./applicationInsightsManagementClientContext";
var ApplicationInsightsManagementClient = /** @class */ (function (_super) {
    __extends(ApplicationInsightsManagementClient, _super);
    /**
     * Initializes a new instance of the ApplicationInsightsManagementClient class.
     * @param credentials Credentials needed for the client to connect to Azure.
     * @param subscriptionId The Azure subscription ID.
     * @param [options] The parameter options
     */
    function ApplicationInsightsManagementClient(credentials, subscriptionId, options) {
        var _this = _super.call(this, credentials, subscriptionId, options) || this;
        _this.operations = new operations.Operations(_this);
        _this.annotations = new operations.Annotations(_this);
        _this.aPIKeys = new operations.APIKeys(_this);
        _this.exportConfigurations = new operations.ExportConfigurations(_this);
        _this.componentCurrentBillingFeatures = new operations.ComponentCurrentBillingFeatures(_this);
        _this.componentQuotaStatus = new operations.ComponentQuotaStatus(_this);
        _this.componentFeatureCapabilities = new operations.ComponentFeatureCapabilities(_this);
        _this.componentAvailableFeatures = new operations.ComponentAvailableFeatures(_this);
        _this.proactiveDetectionConfigurations = new operations.ProactiveDetectionConfigurations(_this);
        _this.components = new operations.Components(_this);
        _this.workItemConfigurations = new operations.WorkItemConfigurations(_this);
        _this.favorites = new operations.Favorites(_this);
        _this.webTestLocations = new operations.WebTestLocations(_this);
        _this.webTests = new operations.WebTests(_this);
        _this.analyticsItems = new operations.AnalyticsItems(_this);
        _this.workbooks = new operations.Workbooks(_this);
        return _this;
    }
    return ApplicationInsightsManagementClient;
}(ApplicationInsightsManagementClientContext));
// Operation Specifications
export { ApplicationInsightsManagementClient, ApplicationInsightsManagementClientContext, Models as ApplicationInsightsManagementModels, Mappers as ApplicationInsightsManagementMappers };
export * from "./operations";
//# sourceMappingURL=applicationInsightsManagementClient.js.map