// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export enum AzureResourceRetrieverErrors {
    BOT_CHANNEL_REGISTRATION_ERROR = 'BOT_CHANNEL_REGISTRATION_ERROR',
    QNA_ACCOUNT_ERROR = 'QNA_ACCOUNT_ERROR',
    LUIS_AUTHORING_ACCOUNT_ERROR = 'LUIS_AUTHORING_ACCOUNT_ERROR',
    LUIS_PREDICTION_ACCOUNT_ERROR = 'LUIS_PREDICTION_ACCOUNT_ERROR',
    APPLICATION_INSIGHTS_ERROR = 'APPLICATION_INSIGHTS_ERROR',
    BLOB_STORAGE_ERROR = 'BLOB_STORAGE_ERROR',
    COSMOS_DB_ERROR = "COSMOS_DB_ERROR"
}