/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { __assign } from "tslib";
import { CloudErrorMapper, BaseResourceMapper } from "@azure/ms-rest-azure-js";
export var CloudError = CloudErrorMapper;
export var BaseResource = BaseResourceMapper;
export var Sku = {
    serializedName: "Sku",
    type: {
        name: "Composite",
        className: "Sku",
        modelProperties: {
            name: {
                required: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            tier: {
                readOnly: true,
                serializedName: "tier",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var Resource = {
    serializedName: "Resource",
    type: {
        name: "Composite",
        className: "Resource",
        modelProperties: {
            id: {
                readOnly: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            name: {
                readOnly: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            location: {
                serializedName: "location",
                type: {
                    name: "String"
                }
            },
            type: {
                readOnly: true,
                serializedName: "type",
                type: {
                    name: "String"
                }
            },
            tags: {
                serializedName: "tags",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "String"
                        }
                    }
                }
            },
            sku: {
                serializedName: "sku",
                type: {
                    name: "Composite",
                    className: "Sku"
                }
            },
            kind: {
                serializedName: "kind",
                type: {
                    name: "String"
                }
            },
            etag: {
                serializedName: "etag",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var BotProperties = {
    serializedName: "BotProperties",
    type: {
        name: "Composite",
        className: "BotProperties",
        modelProperties: {
            displayName: {
                required: true,
                serializedName: "displayName",
                type: {
                    name: "String"
                }
            },
            description: {
                serializedName: "description",
                type: {
                    name: "String"
                }
            },
            iconUrl: {
                serializedName: "iconUrl",
                type: {
                    name: "String"
                }
            },
            endpoint: {
                required: true,
                serializedName: "endpoint",
                type: {
                    name: "String"
                }
            },
            endpointVersion: {
                readOnly: true,
                serializedName: "endpointVersion",
                type: {
                    name: "String"
                }
            },
            msaAppId: {
                required: true,
                serializedName: "msaAppId",
                type: {
                    name: "String"
                }
            },
            configuredChannels: {
                readOnly: true,
                serializedName: "configuredChannels",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            },
            enabledChannels: {
                readOnly: true,
                serializedName: "enabledChannels",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            },
            developerAppInsightKey: {
                serializedName: "developerAppInsightKey",
                type: {
                    name: "String"
                }
            },
            developerAppInsightsApiKey: {
                serializedName: "developerAppInsightsApiKey",
                type: {
                    name: "String"
                }
            },
            developerAppInsightsApplicationId: {
                serializedName: "developerAppInsightsApplicationId",
                type: {
                    name: "String"
                }
            },
            luisAppIds: {
                serializedName: "luisAppIds",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            },
            luisKey: {
                serializedName: "luisKey",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var Bot = {
    serializedName: "Bot",
    type: {
        name: "Composite",
        className: "Bot",
        modelProperties: __assign(__assign({}, Resource.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "BotProperties"
                }
            } })
    }
};
export var Channel = {
    serializedName: "Channel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: {
            serializedName: "channelName",
            clientName: "channelName"
        },
        uberParent: "Channel",
        className: "Channel",
        modelProperties: {
            channelName: {
                required: true,
                serializedName: "channelName",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var BotChannel = {
    serializedName: "BotChannel",
    type: {
        name: "Composite",
        className: "BotChannel",
        modelProperties: __assign(__assign({}, Resource.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "Channel"
                }
            } })
    }
};
export var FacebookPage = {
    serializedName: "FacebookPage",
    type: {
        name: "Composite",
        className: "FacebookPage",
        modelProperties: {
            id: {
                required: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            accessToken: {
                required: true,
                serializedName: "accessToken",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var FacebookChannelProperties = {
    serializedName: "FacebookChannelProperties",
    type: {
        name: "Composite",
        className: "FacebookChannelProperties",
        modelProperties: {
            verifyToken: {
                readOnly: true,
                serializedName: "verifyToken",
                type: {
                    name: "String"
                }
            },
            pages: {
                serializedName: "pages",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "FacebookPage"
                        }
                    }
                }
            },
            appId: {
                required: true,
                serializedName: "appId",
                type: {
                    name: "String"
                }
            },
            appSecret: {
                required: true,
                serializedName: "appSecret",
                type: {
                    name: "String"
                }
            },
            callbackUrl: {
                readOnly: true,
                serializedName: "callbackUrl",
                type: {
                    name: "String"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var FacebookChannel = {
    serializedName: "FacebookChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "FacebookChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "FacebookChannelProperties"
                }
            } })
    }
};
export var EmailChannelProperties = {
    serializedName: "EmailChannelProperties",
    type: {
        name: "Composite",
        className: "EmailChannelProperties",
        modelProperties: {
            emailAddress: {
                required: true,
                serializedName: "emailAddress",
                type: {
                    name: "String"
                }
            },
            password: {
                required: true,
                serializedName: "password",
                type: {
                    name: "String"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var EmailChannel = {
    serializedName: "EmailChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "EmailChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "EmailChannelProperties"
                }
            } })
    }
};
export var MsTeamsChannelProperties = {
    serializedName: "MsTeamsChannelProperties",
    type: {
        name: "Composite",
        className: "MsTeamsChannelProperties",
        modelProperties: {
            enableCalling: {
                serializedName: "enableCalling",
                type: {
                    name: "Boolean"
                }
            },
            callingWebHook: {
                serializedName: "callingWebHook",
                type: {
                    name: "String"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var MsTeamsChannel = {
    serializedName: "MsTeamsChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "MsTeamsChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "MsTeamsChannelProperties"
                }
            } })
    }
};
export var SkypeChannelProperties = {
    serializedName: "SkypeChannelProperties",
    type: {
        name: "Composite",
        className: "SkypeChannelProperties",
        modelProperties: {
            enableMessaging: {
                serializedName: "enableMessaging",
                type: {
                    name: "Boolean"
                }
            },
            enableMediaCards: {
                serializedName: "enableMediaCards",
                type: {
                    name: "Boolean"
                }
            },
            enableVideo: {
                serializedName: "enableVideo",
                type: {
                    name: "Boolean"
                }
            },
            enableCalling: {
                serializedName: "enableCalling",
                type: {
                    name: "Boolean"
                }
            },
            enableScreenSharing: {
                serializedName: "enableScreenSharing",
                type: {
                    name: "Boolean"
                }
            },
            enableGroups: {
                serializedName: "enableGroups",
                type: {
                    name: "Boolean"
                }
            },
            groupsMode: {
                serializedName: "groupsMode",
                type: {
                    name: "String"
                }
            },
            callingWebHook: {
                serializedName: "callingWebHook",
                type: {
                    name: "String"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var SkypeChannel = {
    serializedName: "SkypeChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "SkypeChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "SkypeChannelProperties"
                }
            } })
    }
};
export var KikChannelProperties = {
    serializedName: "KikChannelProperties",
    type: {
        name: "Composite",
        className: "KikChannelProperties",
        modelProperties: {
            userName: {
                required: true,
                serializedName: "userName",
                type: {
                    name: "String"
                }
            },
            apiKey: {
                required: true,
                serializedName: "apiKey",
                type: {
                    name: "String"
                }
            },
            isValidated: {
                serializedName: "isValidated",
                type: {
                    name: "Boolean"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var KikChannel = {
    serializedName: "KikChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "KikChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "KikChannelProperties"
                }
            } })
    }
};
export var WebChatSite = {
    serializedName: "WebChatSite",
    type: {
        name: "Composite",
        className: "WebChatSite",
        modelProperties: {
            siteId: {
                readOnly: true,
                serializedName: "siteId",
                type: {
                    name: "String"
                }
            },
            siteName: {
                required: true,
                serializedName: "siteName",
                type: {
                    name: "String"
                }
            },
            key: {
                readOnly: true,
                serializedName: "key",
                type: {
                    name: "String"
                }
            },
            key2: {
                readOnly: true,
                serializedName: "key2",
                type: {
                    name: "String"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            },
            enablePreview: {
                required: true,
                serializedName: "enablePreview",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var WebChatChannelProperties = {
    serializedName: "WebChatChannelProperties",
    type: {
        name: "Composite",
        className: "WebChatChannelProperties",
        modelProperties: {
            webChatEmbedCode: {
                readOnly: true,
                serializedName: "webChatEmbedCode",
                type: {
                    name: "String"
                }
            },
            sites: {
                serializedName: "sites",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "WebChatSite"
                        }
                    }
                }
            }
        }
    }
};
export var WebChatChannel = {
    serializedName: "WebChatChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "WebChatChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "WebChatChannelProperties"
                }
            } })
    }
};
export var DirectLineSite = {
    serializedName: "DirectLineSite",
    type: {
        name: "Composite",
        className: "DirectLineSite",
        modelProperties: {
            siteId: {
                readOnly: true,
                serializedName: "siteId",
                type: {
                    name: "String"
                }
            },
            siteName: {
                required: true,
                serializedName: "siteName",
                type: {
                    name: "String"
                }
            },
            key: {
                readOnly: true,
                serializedName: "key",
                type: {
                    name: "String"
                }
            },
            key2: {
                readOnly: true,
                serializedName: "key2",
                type: {
                    name: "String"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            },
            isV1Enabled: {
                required: true,
                serializedName: "isV1Enabled",
                type: {
                    name: "Boolean"
                }
            },
            isV3Enabled: {
                required: true,
                serializedName: "isV3Enabled",
                type: {
                    name: "Boolean"
                }
            },
            isSecureSiteEnabled: {
                serializedName: "isSecureSiteEnabled",
                type: {
                    name: "Boolean"
                }
            },
            trustedOrigins: {
                serializedName: "trustedOrigins",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            }
        }
    }
};
export var DirectLineChannelProperties = {
    serializedName: "DirectLineChannelProperties",
    type: {
        name: "Composite",
        className: "DirectLineChannelProperties",
        modelProperties: {
            sites: {
                serializedName: "sites",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "DirectLineSite"
                        }
                    }
                }
            }
        }
    }
};
export var DirectLineChannel = {
    serializedName: "DirectLineChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "DirectLineChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "DirectLineChannelProperties"
                }
            } })
    }
};
export var TelegramChannelProperties = {
    serializedName: "TelegramChannelProperties",
    type: {
        name: "Composite",
        className: "TelegramChannelProperties",
        modelProperties: {
            accessToken: {
                required: true,
                serializedName: "accessToken",
                type: {
                    name: "String"
                }
            },
            isValidated: {
                serializedName: "isValidated",
                type: {
                    name: "Boolean"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var TelegramChannel = {
    serializedName: "TelegramChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "TelegramChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "TelegramChannelProperties"
                }
            } })
    }
};
export var SmsChannelProperties = {
    serializedName: "SmsChannelProperties",
    type: {
        name: "Composite",
        className: "SmsChannelProperties",
        modelProperties: {
            phone: {
                required: true,
                serializedName: "phone",
                type: {
                    name: "String"
                }
            },
            accountSID: {
                required: true,
                serializedName: "accountSID",
                type: {
                    name: "String"
                }
            },
            authToken: {
                required: true,
                serializedName: "authToken",
                type: {
                    name: "String"
                }
            },
            isValidated: {
                serializedName: "isValidated",
                type: {
                    name: "Boolean"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var SmsChannel = {
    serializedName: "SmsChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "SmsChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "SmsChannelProperties"
                }
            } })
    }
};
export var SlackChannelProperties = {
    serializedName: "SlackChannelProperties",
    type: {
        name: "Composite",
        className: "SlackChannelProperties",
        modelProperties: {
            clientId: {
                required: true,
                serializedName: "clientId",
                type: {
                    name: "String"
                }
            },
            clientSecret: {
                required: true,
                serializedName: "clientSecret",
                type: {
                    name: "String"
                }
            },
            verificationToken: {
                required: true,
                serializedName: "verificationToken",
                type: {
                    name: "String"
                }
            },
            landingPageUrl: {
                serializedName: "landingPageUrl",
                type: {
                    name: "String"
                }
            },
            redirectAction: {
                readOnly: true,
                serializedName: "redirectAction",
                type: {
                    name: "String"
                }
            },
            lastSubmissionId: {
                readOnly: true,
                serializedName: "lastSubmissionId",
                type: {
                    name: "String"
                }
            },
            registerBeforeOAuthFlow: {
                readOnly: true,
                serializedName: "registerBeforeOAuthFlow",
                type: {
                    name: "Boolean"
                }
            },
            isValidated: {
                readOnly: true,
                serializedName: "isValidated",
                type: {
                    name: "Boolean"
                }
            },
            isEnabled: {
                required: true,
                serializedName: "isEnabled",
                type: {
                    name: "Boolean"
                }
            }
        }
    }
};
export var SlackChannel = {
    serializedName: "SlackChannel",
    type: {
        name: "Composite",
        polymorphicDiscriminator: Channel.type.polymorphicDiscriminator,
        uberParent: "Channel",
        className: "SlackChannel",
        modelProperties: __assign(__assign({}, Channel.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "SlackChannelProperties"
                }
            } })
    }
};
export var ConnectionItemName = {
    serializedName: "ConnectionItemName",
    type: {
        name: "Composite",
        className: "ConnectionItemName",
        modelProperties: {
            name: {
                readOnly: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var ConnectionSettingParameter = {
    serializedName: "ConnectionSettingParameter",
    type: {
        name: "Composite",
        className: "ConnectionSettingParameter",
        modelProperties: {
            key: {
                serializedName: "key",
                type: {
                    name: "String"
                }
            },
            value: {
                serializedName: "value",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var ConnectionSettingProperties = {
    serializedName: "ConnectionSettingProperties",
    type: {
        name: "Composite",
        className: "ConnectionSettingProperties",
        modelProperties: {
            clientId: {
                serializedName: "clientId",
                type: {
                    name: "String"
                }
            },
            settingId: {
                readOnly: true,
                serializedName: "settingId",
                type: {
                    name: "String"
                }
            },
            clientSecret: {
                serializedName: "clientSecret",
                type: {
                    name: "String"
                }
            },
            scopes: {
                serializedName: "scopes",
                type: {
                    name: "String"
                }
            },
            serviceProviderId: {
                serializedName: "serviceProviderId",
                type: {
                    name: "String"
                }
            },
            serviceProviderDisplayName: {
                serializedName: "serviceProviderDisplayName",
                type: {
                    name: "String"
                }
            },
            parameters: {
                serializedName: "parameters",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "ConnectionSettingParameter"
                        }
                    }
                }
            }
        }
    }
};
export var ConnectionSetting = {
    serializedName: "ConnectionSetting",
    type: {
        name: "Composite",
        className: "ConnectionSetting",
        modelProperties: __assign(__assign({}, Resource.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "ConnectionSettingProperties"
                }
            } })
    }
};
export var ServiceProviderParameter = {
    serializedName: "ServiceProviderParameter",
    type: {
        name: "Composite",
        className: "ServiceProviderParameter",
        modelProperties: {
            name: {
                readOnly: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            type: {
                readOnly: true,
                serializedName: "type",
                type: {
                    name: "String"
                }
            },
            displayName: {
                readOnly: true,
                serializedName: "displayName",
                type: {
                    name: "String"
                }
            },
            description: {
                readOnly: true,
                serializedName: "description",
                type: {
                    name: "String"
                }
            },
            helpUrl: {
                readOnly: true,
                serializedName: "helpUrl",
                type: {
                    name: "String"
                }
            },
            default: {
                readOnly: true,
                serializedName: "default",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var ServiceProviderProperties = {
    serializedName: "ServiceProviderProperties",
    type: {
        name: "Composite",
        className: "ServiceProviderProperties",
        modelProperties: {
            id: {
                readOnly: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            displayName: {
                readOnly: true,
                serializedName: "displayName",
                type: {
                    name: "String"
                }
            },
            serviceProviderName: {
                readOnly: true,
                serializedName: "serviceProviderName",
                type: {
                    name: "String"
                }
            },
            devPortalUrl: {
                readOnly: true,
                serializedName: "devPortalUrl",
                type: {
                    name: "String"
                }
            },
            iconUrl: {
                readOnly: true,
                serializedName: "iconUrl",
                type: {
                    name: "String"
                }
            },
            parameters: {
                serializedName: "parameters",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "ServiceProviderParameter"
                        }
                    }
                }
            }
        }
    }
};
export var ServiceProvider = {
    serializedName: "ServiceProvider",
    type: {
        name: "Composite",
        className: "ServiceProvider",
        modelProperties: {
            properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "ServiceProviderProperties"
                }
            }
        }
    }
};
export var ServiceProviderResponseList = {
    serializedName: "ServiceProviderResponseList",
    type: {
        name: "Composite",
        className: "ServiceProviderResponseList",
        modelProperties: {
            nextLink: {
                serializedName: "nextLink",
                type: {
                    name: "String"
                }
            },
            value: {
                readOnly: true,
                serializedName: "value",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "ServiceProvider"
                        }
                    }
                }
            }
        }
    }
};
export var ErrorBody = {
    serializedName: "ErrorBody",
    type: {
        name: "Composite",
        className: "ErrorBody",
        modelProperties: {
            code: {
                required: true,
                serializedName: "code",
                type: {
                    name: "String"
                }
            },
            message: {
                required: true,
                serializedName: "message",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var ErrorModel = {
    serializedName: "Error",
    type: {
        name: "Composite",
        className: "ErrorModel",
        modelProperties: {
            error: {
                serializedName: "error",
                type: {
                    name: "Composite",
                    className: "ErrorBody"
                }
            }
        }
    }
};
export var OperationDisplayInfo = {
    serializedName: "OperationDisplayInfo",
    type: {
        name: "Composite",
        className: "OperationDisplayInfo",
        modelProperties: {
            description: {
                serializedName: "description",
                type: {
                    name: "String"
                }
            },
            operation: {
                serializedName: "operation",
                type: {
                    name: "String"
                }
            },
            provider: {
                serializedName: "provider",
                type: {
                    name: "String"
                }
            },
            resource: {
                serializedName: "resource",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var OperationEntity = {
    serializedName: "OperationEntity",
    type: {
        name: "Composite",
        className: "OperationEntity",
        modelProperties: {
            name: {
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            display: {
                serializedName: "display",
                type: {
                    name: "Composite",
                    className: "OperationDisplayInfo"
                }
            },
            origin: {
                serializedName: "origin",
                type: {
                    name: "String"
                }
            },
            properties: {
                serializedName: "properties",
                type: {
                    name: "Object"
                }
            }
        }
    }
};
export var CheckNameAvailabilityRequestBody = {
    serializedName: "CheckNameAvailabilityRequestBody",
    type: {
        name: "Composite",
        className: "CheckNameAvailabilityRequestBody",
        modelProperties: {
            name: {
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            type: {
                serializedName: "type",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var CheckNameAvailabilityResponseBody = {
    serializedName: "CheckNameAvailabilityResponseBody",
    type: {
        name: "Composite",
        className: "CheckNameAvailabilityResponseBody",
        modelProperties: {
            valid: {
                serializedName: "valid",
                type: {
                    name: "Boolean"
                }
            },
            message: {
                serializedName: "message",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var EnterpriseChannelCheckNameAvailabilityRequest = {
    serializedName: "EnterpriseChannelCheckNameAvailabilityRequest",
    type: {
        name: "Composite",
        className: "EnterpriseChannelCheckNameAvailabilityRequest",
        modelProperties: {
            name: {
                serializedName: "name",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var EnterpriseChannelCheckNameAvailabilityResponse = {
    serializedName: "EnterpriseChannelCheckNameAvailabilityResponse",
    type: {
        name: "Composite",
        className: "EnterpriseChannelCheckNameAvailabilityResponse",
        modelProperties: {
            valid: {
                serializedName: "valid",
                type: {
                    name: "Boolean"
                }
            },
            message: {
                serializedName: "message",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var EnterpriseChannelNode = {
    serializedName: "EnterpriseChannelNode",
    type: {
        name: "Composite",
        className: "EnterpriseChannelNode",
        modelProperties: {
            id: {
                readOnly: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            state: {
                serializedName: "state",
                type: {
                    name: "String"
                }
            },
            name: {
                required: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            azureSku: {
                required: true,
                serializedName: "azureSku",
                type: {
                    name: "String"
                }
            },
            azureLocation: {
                required: true,
                serializedName: "azureLocation",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var EnterpriseChannelProperties = {
    serializedName: "EnterpriseChannelProperties",
    type: {
        name: "Composite",
        className: "EnterpriseChannelProperties",
        modelProperties: {
            state: {
                serializedName: "state",
                type: {
                    name: "String"
                }
            },
            nodes: {
                required: true,
                serializedName: "nodes",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "EnterpriseChannelNode"
                        }
                    }
                }
            }
        }
    }
};
export var EnterpriseChannel = {
    serializedName: "EnterpriseChannel",
    type: {
        name: "Composite",
        className: "EnterpriseChannel",
        modelProperties: __assign(__assign({}, Resource.type.modelProperties), { properties: {
                serializedName: "properties",
                type: {
                    name: "Composite",
                    className: "EnterpriseChannelProperties"
                }
            } })
    }
};
export var BotResponseList = {
    serializedName: "BotResponseList",
    type: {
        name: "Composite",
        className: "BotResponseList",
        modelProperties: {
            nextLink: {
                serializedName: "nextLink",
                type: {
                    name: "String"
                }
            },
            value: {
                readOnly: true,
                serializedName: "",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "Bot"
                        }
                    }
                }
            }
        }
    }
};
export var ChannelResponseList = {
    serializedName: "ChannelResponseList",
    type: {
        name: "Composite",
        className: "ChannelResponseList",
        modelProperties: {
            nextLink: {
                serializedName: "nextLink",
                type: {
                    name: "String"
                }
            },
            value: {
                readOnly: true,
                serializedName: "",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "BotChannel"
                        }
                    }
                }
            }
        }
    }
};
export var OperationEntityListResult = {
    serializedName: "OperationEntityListResult",
    type: {
        name: "Composite",
        className: "OperationEntityListResult",
        modelProperties: {
            nextLink: {
                serializedName: "nextLink",
                type: {
                    name: "String"
                }
            },
            value: {
                serializedName: "",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "OperationEntity"
                        }
                    }
                }
            }
        }
    }
};
export var ConnectionSettingResponseList = {
    serializedName: "ConnectionSettingResponseList",
    type: {
        name: "Composite",
        className: "ConnectionSettingResponseList",
        modelProperties: {
            nextLink: {
                serializedName: "nextLink",
                type: {
                    name: "String"
                }
            },
            value: {
                readOnly: true,
                serializedName: "",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "ConnectionSetting"
                        }
                    }
                }
            }
        }
    }
};
export var EnterpriseChannelResponseList = {
    serializedName: "EnterpriseChannelResponseList",
    type: {
        name: "Composite",
        className: "EnterpriseChannelResponseList",
        modelProperties: {
            nextLink: {
                serializedName: "nextLink",
                type: {
                    name: "String"
                }
            },
            value: {
                readOnly: true,
                serializedName: "",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "EnterpriseChannel"
                        }
                    }
                }
            }
        }
    }
};
export var discriminators = {
    'Channel': Channel,
    'Channel.FacebookChannel': FacebookChannel,
    'Channel.EmailChannel': EmailChannel,
    'Channel.MsTeamsChannel': MsTeamsChannel,
    'Channel.SkypeChannel': SkypeChannel,
    'Channel.KikChannel': KikChannel,
    'Channel.WebChatChannel': WebChatChannel,
    'Channel.DirectLineChannel': DirectLineChannel,
    'Channel.TelegramChannel': TelegramChannel,
    'Channel.SmsChannel': SmsChannel,
    'Channel.SlackChannel': SlackChannel
};
//# sourceMappingURL=mappers.js.map