/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export var acceptLanguage = {
    parameterPath: "acceptLanguage",
    mapper: {
        serializedName: "accept-language",
        defaultValue: 'en-US',
        type: {
            name: "String"
        }
    }
};
export var apiVersion = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        serializedName: "api-version",
        type: {
            name: "String"
        }
    }
};
export var channelName0 = {
    parameterPath: "channelName",
    mapper: {
        required: true,
        serializedName: "channelName",
        type: {
            name: "Enum",
            allowedValues: [
                "FacebookChannel",
                "EmailChannel",
                "KikChannel",
                "TelegramChannel",
                "SlackChannel",
                "MsTeamsChannel",
                "SkypeChannel",
                "WebChatChannel",
                "DirectLineChannel",
                "SmsChannel"
            ]
        }
    }
};
export var channelName1 = {
    parameterPath: "channelName",
    mapper: {
        required: true,
        serializedName: "channelName",
        constraints: {
            MaxLength: 64,
            MinLength: 2,
            Pattern: /^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/
        },
        type: {
            name: "String"
        }
    }
};
export var connectionName = {
    parameterPath: "connectionName",
    mapper: {
        required: true,
        serializedName: "connectionName",
        constraints: {
            MaxLength: 64,
            MinLength: 2,
            Pattern: /^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/
        },
        type: {
            name: "String"
        }
    }
};
export var nextPageLink = {
    parameterPath: "nextPageLink",
    mapper: {
        required: true,
        serializedName: "nextLink",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var resourceGroupName = {
    parameterPath: "resourceGroupName",
    mapper: {
        required: true,
        serializedName: "resourceGroupName",
        constraints: {
            MaxLength: 64,
            MinLength: 2,
            Pattern: /^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/
        },
        type: {
            name: "String"
        }
    }
};
export var resourceName = {
    parameterPath: "resourceName",
    mapper: {
        required: true,
        serializedName: "resourceName",
        constraints: {
            MaxLength: 64,
            MinLength: 2,
            Pattern: /^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/
        },
        type: {
            name: "String"
        }
    }
};
export var subscriptionId = {
    parameterPath: "subscriptionId",
    mapper: {
        required: true,
        serializedName: "subscriptionId",
        type: {
            name: "String"
        }
    }
};
//# sourceMappingURL=parameters.js.map