export declare enum BotProjectDeployLoggerType {
  PROVISION_INFO = 'PROVISION_INFO',
  PROVISION_ERROR = 'PROVISION_ERROR',
  PROVISION_WARNING = 'PROVISION_WARNING',
  PROVISION_SUCCESS = 'PROVISION_SUCCESS',
  PROVISION_ERROR_DETAILS = 'PROVISION_ERROR_DETAILS',
  DEPLOY_INFO = 'DEPLOY_INFO',
  DEPLOY_ERROR = 'DEPLOY_ERROR',
  DEPLOY_WARNING = 'DEPLOY_WARNING',
  DEPLOY_SUCCESS = 'DEPLOY_SUCCESS',
}
//# sourceMappingURL=botProjectLoggerType.d.ts.map
