/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
export var acceptLanguage = {
    parameterPath: "acceptLanguage",
    mapper: {
        serializedName: "accept-language",
        defaultValue: 'en-US',
        type: {
            name: "String"
        }
    }
};
export var annotationId = {
    parameterPath: "annotationId",
    mapper: {
        required: true,
        serializedName: "annotationId",
        type: {
            name: "String"
        }
    }
};
export var apiVersion = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        serializedName: "api-version",
        type: {
            name: "String"
        }
    }
};
export var canFetchContent = {
    parameterPath: [
        "options",
        "canFetchContent"
    ],
    mapper: {
        serializedName: "canFetchContent",
        type: {
            name: "Boolean"
        }
    }
};
export var category = {
    parameterPath: "category",
    mapper: {
        required: true,
        serializedName: "category",
        type: {
            name: "String"
        }
    }
};
export var componentName = {
    parameterPath: "componentName",
    mapper: {
        required: true,
        serializedName: "componentName",
        type: {
            name: "String"
        }
    }
};
export var configurationId = {
    parameterPath: "configurationId",
    mapper: {
        required: true,
        serializedName: "ConfigurationId",
        type: {
            name: "String"
        }
    }
};
export var end = {
    parameterPath: "end",
    mapper: {
        required: true,
        serializedName: "end",
        type: {
            name: "String"
        }
    }
};
export var exportId = {
    parameterPath: "exportId",
    mapper: {
        required: true,
        serializedName: "exportId",
        type: {
            name: "String"
        }
    }
};
export var favoriteId = {
    parameterPath: "favoriteId",
    mapper: {
        required: true,
        serializedName: "favoriteId",
        type: {
            name: "String"
        }
    }
};
export var favoriteType = {
    parameterPath: [
        "options",
        "favoriteType"
    ],
    mapper: {
        serializedName: "favoriteType",
        defaultValue: 'shared',
        type: {
            name: "Enum",
            allowedValues: [
                "shared",
                "user"
            ]
        }
    }
};
export var id = {
    parameterPath: [
        "options",
        "id"
    ],
    mapper: {
        serializedName: "id",
        type: {
            name: "String"
        }
    }
};
export var includeContent = {
    parameterPath: [
        "options",
        "includeContent"
    ],
    mapper: {
        serializedName: "includeContent",
        type: {
            name: "Boolean"
        }
    }
};
export var keyId = {
    parameterPath: "keyId",
    mapper: {
        required: true,
        serializedName: "keyId",
        type: {
            name: "String"
        }
    }
};
export var name = {
    parameterPath: [
        "options",
        "name"
    ],
    mapper: {
        serializedName: "name",
        type: {
            name: "String"
        }
    }
};
export var nextPageLink = {
    parameterPath: "nextPageLink",
    mapper: {
        required: true,
        serializedName: "nextLink",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
export var overrideItem = {
    parameterPath: [
        "options",
        "overrideItem"
    ],
    mapper: {
        serializedName: "overrideItem",
        type: {
            name: "Boolean"
        }
    }
};
export var purgeId = {
    parameterPath: "purgeId",
    mapper: {
        required: true,
        serializedName: "purgeId",
        type: {
            name: "String"
        }
    }
};
export var resourceGroupName = {
    parameterPath: "resourceGroupName",
    mapper: {
        required: true,
        serializedName: "resourceGroupName",
        type: {
            name: "String"
        }
    }
};
export var resourceName = {
    parameterPath: "resourceName",
    mapper: {
        required: true,
        serializedName: "resourceName",
        type: {
            name: "String"
        }
    }
};
export var scope = {
    parameterPath: [
        "options",
        "scope"
    ],
    mapper: {
        serializedName: "scope",
        defaultValue: 'shared',
        type: {
            name: "String"
        }
    }
};
export var scopePath = {
    parameterPath: "scopePath",
    mapper: {
        required: true,
        serializedName: "scopePath",
        type: {
            name: "String"
        }
    }
};
export var sourceType = {
    parameterPath: [
        "options",
        "sourceType"
    ],
    mapper: {
        serializedName: "sourceType",
        type: {
            name: "String"
        }
    }
};
export var start = {
    parameterPath: "start",
    mapper: {
        required: true,
        serializedName: "start",
        type: {
            name: "String"
        }
    }
};
export var subscriptionId = {
    parameterPath: "subscriptionId",
    mapper: {
        required: true,
        serializedName: "subscriptionId",
        type: {
            name: "String"
        }
    }
};
export var tags = {
    parameterPath: [
        "options",
        "tags"
    ],
    mapper: {
        serializedName: "tags",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Csv
};
export var type = {
    parameterPath: [
        "options",
        "type"
    ],
    mapper: {
        serializedName: "type",
        defaultValue: 'none',
        type: {
            name: "String"
        }
    }
};
export var webTestName = {
    parameterPath: "webTestName",
    mapper: {
        required: true,
        serializedName: "webTestName",
        type: {
            name: "String"
        }
    }
};
export var workItemConfigId = {
    parameterPath: "workItemConfigId",
    mapper: {
        required: true,
        serializedName: "workItemConfigId",
        type: {
            name: "String"
        }
    }
};
//# sourceMappingURL=parameters.js.map